In [3]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9994, 21)

In [5]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [7]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [8]:
df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [9]:
df["Delivery Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [10]:
df["Delivery Days"].describe()

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Delivery Days, dtype: float64

In [11]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Delivery Days    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Delivery Days"].value_counts().sort_index()

Delivery Days
0     519
1     369
2    1334
3    1005
4    2774
5    2169
6    1203
7     621
Name: count, dtype: int64

In [14]:
df.groupby("Discount")["Profit"].agg(["count", "mean", "sum"]).round(2)

          count    mean        sum
Discount
0.00       4798   66.90  320987.60
0.10         94   96.06    9029.18
0.15         52   27.29    1418.99
0.20       3657   24.70   90337.31
0.30        227  -45.68  -10369.28
0.32         27  -88.56   -2391.14
0.40        206 -111.93  -23057.05
0.45         11 -226.65   -2493.11
0.50         66 -310.70  -20506.43
0.60        138  -43.08   -5944.66
0.70        418  -95.87  -40075.36
0.80        300 -101.80  -30539.04

In [15]:
df.groupby("Category")[["Sales", "Profit"]].sum().round(2)

                     Sales     Profit
Category
Furniture        741999.80   18451.27
Office Supplies  719047.03  122490.80
Technology       836154.03  145454.95

In [16]:
# Group the data by Sub-Category and calculate total Sales and total Profit
# This helps us identify which product sub-categories are contributing
# the most and least to overall profitability.

subcategory_profit = (
    df.groupby("Sub-Category")[["Sales", "Profit"]]
      .sum()
      .sort_values("Profit")
      .round(2)
)

# Display the result
subcategory_profit

                  Sales    Profit
Sub-Category
Tables        206965.53 -17725.48
Bookcases     114880.00  -3472.56
Supplies       46673.54  -1189.10
Fasteners       3024.28    949.52
Machines      189238.63   3384.76
Labels         12486.31   5546.25
Art            27118.79   6527.79
Envelopes      16476.40   6964.18
Furnishings    91705.16  13059.14
Appliances    107532.16  18138.01
Storage       223843.61  21278.83
Chairs        328449.10  26590.17
Binders       203412.73  30221.76
Paper          78479.21  34053.57
Accessories   167380.32  41936.64
Phones        330007.05  44515.73
Copiers       149528.03  55617.82

In [17]:
# Calculate profit margin for each sub-category.
# Profit Margin = (Profit / Sales) × 100
# This tells us how much profit the business makes for every ₹/$100 of sales.

subcategory_profit["Profit Margin %"] = (
    subcategory_profit["Profit"] /
    subcategory_profit["Sales"] * 100
).round(2)

# Display Sales, Profit, and Profit Margin together
subcategory_profit

                  Sales    Profit  Profit Margin %
Sub-Category
Tables        206965.53 -17725.48            -8.56
Bookcases     114880.00  -3472.56            -3.02
Supplies       46673.54  -1189.10            -2.55
Fasteners       3024.28    949.52            31.40
Machines      189238.63   3384.76             1.79
Labels         12486.31   5546.25            44.42
Art            27118.79   6527.79            24.07
Envelopes      16476.40   6964.18            42.27
Furnishings    91705.16  13059.14            14.24
Appliances    107532.16  18138.01            16.87
Storage       223843.61  21278.83             9.51
Chairs        328449.10  26590.17             8.10
Binders       203412.73  30221.76            14.86
Paper          78479.21  34053.57            43.39
Accessories   167380.32  41936.64            25.05
Phones        330007.05  44515.73            13.49
Copiers       149528.03  55617.82            37.20

In [18]:
# Select only Tables and Bookcases.
# These two sub-categories have negative overall profit,
# so we want to investigate their discount levels.

furniture_loss = df[
    df["Sub-Category"].isin(["Tables", "Bookcases"])
]

# Calculate total sales, total profit, average discount,
# and maximum discount for each sub-category.

furniture_discount = furniture_loss.groupby("Sub-Category").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Average_Discount=("Discount", "mean"),
    Maximum_Discount=("Discount", "max")
).round(2)

# Display the result
furniture_discount

                  Sales    Profit  Average_Discount  Maximum_Discount
Sub-Category
Bookcases     114880.00  -3472.56              0.21               0.7
Tables        206965.53 -17725.48              0.26               0.5

In [19]:
# Analyze profitability at each discount level.
# This helps us see whether higher discounts are associated
# with lower profit for Tables and Bookcases.

discount_profit = (
    furniture_loss
    .groupby(["Sub-Category", "Discount"])["Profit"]
    .agg(
        Transactions="count",
        Total_Profit="sum",
        Average_Profit="mean"
    )
    .round(2)
)

# Display the result
discount_profit

                       Transactions  Total_Profit  Average_Profit
Sub-Category Discount
Bookcases    0.00                60       6075.71          101.26
             0.15                52       1418.99           27.29
             0.20                46        130.50            2.84
             0.30                10       -555.87          -55.59
             0.32                27      -2391.14          -88.56
             0.50                18      -4255.81         -236.43
             0.70                15      -3894.94         -259.66
Tables       0.00                72      13276.30          184.39
             0.20                71       -303.56           -4.28
             0.30                54      -3402.33          -63.01
             0.40                75     -16187.40         -215.83
             0.45                11      -2493.11         -226.65
             0.50                36      -8615.39         -239.32

In [20]:
# Filter the dataset to Tables and Bookcases.
# We want to investigate where these loss-making products
# are generating negative profit.

furniture_loss = df[
    df["Sub-Category"].isin(["Tables", "Bookcases"])
]

# Group the data by Region and Sub-Category.
# Calculate total Sales and total Profit for each combination.

region_loss = (
    furniture_loss
    .groupby(["Region", "Sub-Category"])[["Sales", "Profit"]]
    .sum()
    .round(2)
)

# Display the regional profitability
region_loss

                         Sales    Profit
Region  Sub-Category
Central Bookcases     24157.18  -1997.90
        Tables        39154.97  -3559.65
East    Bookcases     43819.33  -1167.63
        Tables        39139.81 -11025.38
South   Bookcases     10899.36   1339.49
        Tables        43916.19  -4623.06
West    Bookcases     36004.12  -1646.51
        Tables        84754.56   1482.61

In [21]:
# Calculate Profit Margin for each Region and Sub-Category.
# This helps us compare profitability across regions
# even when sales volumes are different.

region_loss["Profit Margin %"] = (
    region_loss["Profit"] /
    region_loss["Sales"] * 100
).round(2)

# Display the final result
region_loss

                         Sales    Profit  Profit Margin %
Region  Sub-Category
Central Bookcases     24157.18  -1997.90            -8.27
        Tables        39154.97  -3559.65            -9.09
East    Bookcases     43819.33  -1167.63            -2.66
        Tables        39139.81 -11025.38           -28.17
South   Bookcases     10899.36   1339.49            12.29
        Tables        43916.19  -4623.06           -10.53
West    Bookcases     36004.12  -1646.51            -4.57
        Tables        84754.56   1482.61             1.75

In [22]:
# Filter the dataset to only Table products.
# We are investigating which individual products
# contribute most to the overall Table loss.

tables = df[
    df["Sub-Category"] == "Tables"
]

# Group by Product Name and calculate:
# 1. Total Sales
# 2. Total Profit
# 3. Average Discount
# 4. Number of transactions

table_products = (
    tables
    .groupby("Product Name")
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Average_Discount=("Discount", "mean"),
        Transactions=("Product Name", "count")
    )
    .sort_values("Profit")
    .round(2)
)

# Display the products from the biggest losses
# to the highest profits.
table_products

,Sales,Profit,Average_Discount,Transactions
Product Name,,,,
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases,9917.64,-2876.12,0.28,5
Bush Advantage Collection Racetrack Conference Table,9544.72,-1934.40,0.35,7
Balt Solid Wood Round Tables,6518.75,-1201.06,0.20,4
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables,1706.25,-1148.44,0.48,3
"Riverside Furniture Oval Coffee Table, Oval End Table, End Table with Drawer",4446.18,-1147.40,0.30,5
Bretford Just In Time Height-Adjustable Multi-Task Work Tables,5634.90,-964.19,0.22,4
"Bevis Oval Conference Table, Walnut",6942.07,-856.01,0.28,8
BPI Conference Tables,2241.87,-795.97,0.37,5
Hon 94000 Series Round Tables,7404.50,-681.21,0.16,5
"Chromcraft Bull-Nose Wood 48"" x 96"" Rectangular Conference Tables",4297.64,-611.59,0.33,6
Hon Racetrack Conference Tables,3963.90,-598.52,0.28,6
Bevis Rectangular Conference Tables,1007.26,-586.84,0.48,4
Bretford CR4500 Series Slim Rectangular Table,7242.77,-532.76,0.26,8
"Bevis Round Conference Table Top, X-Base",2671.42,-519.94,0.27,6
KI Conference Tables,2140.88,-479.22,0.32,8
"Bevis Traditional Conference Table Top, Plinth Base",2033.50,-456.70,0.33,3
Chromcraft Rectangular Conference Tables,4952.67,-450.24,0.32,9
Bevis Boat-Shaped Conference Table,2542.47,-445.59,0.32,6
Riverside Furniture Stanwyck Manor Table Series,917.92,-415.93,0.37,3
"Chromcraft 48"" x 96"" Racetrack Double Pedestal Table",5098.18,-404.01,0.32,6
Hon 2111 Invitation Series Corner Table,3140.55,-401.99,0.20,4
"Iceberg OfficeWorks 42"" Round Tables",3457.44,-392.55,0.20,7
Balt Split Level Computer Training Table,1040.62,-357.98,0.38,5
"Lesro Round Back Collection Coffee Table, End Table",2847.78,-328.59,0.29,8
Bretford Rectangular Conference Table Tops,12995.29,-327.23,0.25,12
Hon Rectangular Conference Tables,3481.52,-295.82,0.32,4
KI Adjustable-Height Table,4552.64,-248.48,0.24,18
Hon 5100 Series Wood Tables,5965.09,-238.60,0.21,7
Balt Solid Wood Rectangular Table,828.10,-216.25,0.26,4
Laminate Occasional Tables,2096.17,-206.53,0.23,3
"Bevis Round Bullnose 29"" High Table Top",4544.92,-192.19,0.26,5
Chromcraft Round Conference Tables,8209.06,-189.98,0.26,13
"Hon 30"" x 60"" Table with Locking Drawer",1296.03,-177.35,0.33,3
Bevis 44 x 96 Conference Tables,3253.22,-164.72,0.18,5
Hon 61000 Series Interactive Training Tables,653.12,-148.40,0.31,9
"Bush Andora Conference Table, Maple/Graphite Gray Finish",1436.23,-143.62,0.30,4
Hon 2111 Invitation Series Straight Table,2040.05,-115.31,0.27,7
"Barricks 18"" x 48"" Non-Folding Utility Table with Bottom Storage Shelf",1088.64,-104.83,0.32,5
"Office Impressions End Table, 20-1/2""H x 24""W x 20""D",5801.82,-66.83,0.18,5
Bevis Round Conference Room Tables and Bases,519.94,-39.44,0.25,2
Anderson Hickey Conga Table Tops & Accessories,51.78,-17.51,0.30,2
"Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table",2298.11,-12.13,0.18,9
"Barricks Non-Folding Utility Table with Steel Legs, Laminate Tops",136.46,15.35,0.20,1
Safco Drafting Table,638.82,34.07,0.20,4
"SAFCO PlanMaster Boards, 60w x 37-1/2d, White Melamine",2979.00,54.72,0.26,5
Hon 4060 Series Tables,1231.56,96.29,0.20,4
"Chromcraft Bull-Nose Wood Round Conference Table Top, Wood Base",3354.89,100.21,0.18,6
Bevis Round Conference Table Top & Single Column Base,2297.54,100.97,0.22,5
Bush Advantage Collection Round Conference Table,3401.60,210.47,0.24,4
"Bush Cubix Conference Tables, Fully Assembled",3603.29,311.82,0.20,4
Global Adaptabilities Conference Tables,3540.35,354.03,0.15,4
"Hon Practical Foundations 30 x 60 Training Table, Light Gray/Charcoal",4334.83,430.07,0.18,6
Bevis 36 x 72 Conference Tables,4332.25,448.16,0.16,8
Bretford CR8500 Series Meeting Room Furniture,6776.56,461.13,0.18,6
Hon Non-Folding Utility Tables,3775.65,541.65,0.20,5
"SAFCO PlanMaster Heigh-Adjustable Drafting Table Base, 43w x 30d x 30-37h, Black",3739.12,608.04,0.28,5

In [23]:
# Select only products where total profit is negative.
# These products are contributing to the overall Table loss.

loss_making_tables = table_products[
    table_products["Profit"] < 0
]

# Display the loss-making Table products
loss_making_tables

,Sales,Profit,Average_Discount,Transactions
Product Name,,,,
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases,9917.64,-2876.12,0.28,5
Bush Advantage Collection Racetrack Conference Table,9544.72,-1934.40,0.35,7
Balt Solid Wood Round Tables,6518.75,-1201.06,0.20,4
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables,1706.25,-1148.44,0.48,3
"Riverside Furniture Oval Coffee Table, Oval End Table, End Table with Drawer",4446.18,-1147.40,0.30,5
Bretford Just In Time Height-Adjustable Multi-Task Work Tables,5634.90,-964.19,0.22,4
"Bevis Oval Conference Table, Walnut",6942.07,-856.01,0.28,8
BPI Conference Tables,2241.87,-795.97,0.37,5
Hon 94000 Series Round Tables,7404.50,-681.21,0.16,5
"Chromcraft Bull-Nose Wood 48"" x 96"" Rectangular Conference Tables",4297.64,-611.59,0.33,6
Hon Racetrack Conference Tables,3963.90,-598.52,0.28,6
Bevis Rectangular Conference Tables,1007.26,-586.84,0.48,4
Bretford CR4500 Series Slim Rectangular Table,7242.77,-532.76,0.26,8
"Bevis Round Conference Table Top, X-Base",2671.42,-519.94,0.27,6
KI Conference Tables,2140.88,-479.22,0.32,8
"Bevis Traditional Conference Table Top, Plinth Base",2033.50,-456.70,0.33,3
Chromcraft Rectangular Conference Tables,4952.67,-450.24,0.32,9
Bevis Boat-Shaped Conference Table,2542.47,-445.59,0.32,6
Riverside Furniture Stanwyck Manor Table Series,917.92,-415.93,0.37,3
"Chromcraft 48"" x 96"" Racetrack Double Pedestal Table",5098.18,-404.01,0.32,6
Hon 2111 Invitation Series Corner Table,3140.55,-401.99,0.20,4
"Iceberg OfficeWorks 42"" Round Tables",3457.44,-392.55,0.20,7
Balt Split Level Computer Training Table,1040.62,-357.98,0.38,5
"Lesro Round Back Collection Coffee Table, End Table",2847.78,-328.59,0.29,8
Bretford Rectangular Conference Table Tops,12995.29,-327.23,0.25,12
Hon Rectangular Conference Tables,3481.52,-295.82,0.32,4
KI Adjustable-Height Table,4552.64,-248.48,0.24,18
Hon 5100 Series Wood Tables,5965.09,-238.60,0.21,7
Balt Solid Wood Rectangular Table,828.10,-216.25,0.26,4
Laminate Occasional Tables,2096.17,-206.53,0.23,3
"Bevis Round Bullnose 29"" High Table Top",4544.92,-192.19,0.26,5
Chromcraft Round Conference Tables,8209.06,-189.98,0.26,13
"Hon 30"" x 60"" Table with Locking Drawer",1296.03,-177.35,0.33,3
Bevis 44 x 96 Conference Tables,3253.22,-164.72,0.18,5
Hon 61000 Series Interactive Training Tables,653.12,-148.40,0.31,9
"Bush Andora Conference Table, Maple/Graphite Gray Finish",1436.23,-143.62,0.30,4
Hon 2111 Invitation Series Straight Table,2040.05,-115.31,0.27,7
"Barricks 18"" x 48"" Non-Folding Utility Table with Bottom Storage Shelf",1088.64,-104.83,0.32,5
"Office Impressions End Table, 20-1/2""H x 24""W x 20""D",5801.82,-66.83,0.18,5
Bevis Round Conference Room Tables and Bases,519.94,-39.44,0.25,2
Anderson Hickey Conga Table Tops & Accessories,51.78,-17.51,0.30,2
"Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table",2298.11,-12.13,0.18,9

In [24]:
# Select the 10 Table products with the largest total losses.
# Sorting by Profit in ascending order puts the biggest losses first.

top_10_table_losses = (
    table_products
    .sort_values("Profit", ascending=True)
    .head(10)
)

# Display the top 10 loss-making Table products
top_10_table_losses

,Sales,Profit,Average_Discount,Transactions
Product Name,,,,
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases,9917.64,-2876.12,0.28,5
Bush Advantage Collection Racetrack Conference Table,9544.72,-1934.40,0.35,7
Balt Solid Wood Round Tables,6518.75,-1201.06,0.20,4
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables,1706.25,-1148.44,0.48,3
"Riverside Furniture Oval Coffee Table, Oval End Table, End Table with Drawer",4446.18,-1147.40,0.30,5
Bretford Just In Time Height-Adjustable Multi-Task Work Tables,5634.90,-964.19,0.22,4
"Bevis Oval Conference Table, Walnut",6942.07,-856.01,0.28,8
BPI Conference Tables,2241.87,-795.97,0.37,5
Hon 94000 Series Round Tables,7404.50,-681.21,0.16,5
"Chromcraft Bull-Nose Wood 48"" x 96"" Rectangular Conference Tables",4297.64,-611.59,0.33,6

In [25]:
# Calculate the total loss across all Table products.

total_table_loss = table_products["Profit"].sum()

# Calculate the combined profit/loss of the 10 worst-performing products.

top_10_loss = top_10_table_losses["Profit"].sum()

# Calculate what percentage of the total Table loss
# comes from these 10 products.

loss_contribution = (top_10_loss / total_table_loss * 100).round(2)

print("Total Table Profit/Loss:", round(total_table_loss, 2))
print("Top 10 Table Profit/Loss:", round(top_10_loss, 2))
print("Top 10 Loss Contribution (%):", loss_contribution)

Total Table Profit/Loss: -17725.49
Top 10 Table Profit/Loss: -12216.39
Top 10 Loss Contribution (%): 68.92

In [26]:
# Create the Year column from Order Date.
# This will allow us to analyze yearly performance in Power BI.

df["Year"] = df["Order Date"].dt.year


# Create the Month column.
# This extracts the month number from Order Date.

df["Month"] = df["Order Date"].dt.month


# Create a Month-Year column.
# This is useful for displaying monthly trends in Power BI.

df["Month-Year"] = df["Order Date"].dt.to_period("M").astype(str)


# Create Profit Margin.
# Profit Margin = Profit / Sales × 100

df["Profit Margin %"] = (
    df["Profit"] / df["Sales"] * 100
).round(2)


# Create a Profit/Loss Status column.
# If Profit is greater than or equal to zero,
# classify the transaction as Profitable.
# Otherwise, classify it as Loss.

df["Profit/Loss Status"] = df["Profit"].apply(
    lambda x: "Profit" if x >= 0 else "Loss"
)


# Display the first 5 rows to verify the new columns.

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sales,Quantity,Discount,Profit,Delivery Days,Year,Month,Month-Year,Profit Margin %,Profit/Loss Status
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,3,2016,11,2016-11,16.00,Profit
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,3,2016,11,2016-11,30.00,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,4,2016,6,2016-06,47.00,Profit
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,7,2015,10,2015-10,-40.00,Loss
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,7,2015,10,2015-10,11.25,Profit

In [27]:
# Create groups for different discount levels.
# This makes it easier to analyze the relationship
# between discount levels and profitability.

def classify_discount(discount):
    
    # No discount
    if discount == 0:
        return "0%"
    
    # Low discount
    elif discount <= 0.20:
        return "1-20%"
    
    # Medium discount
    elif discount <= 0.40:
        return "21-40%"
    
    # High discount
    else:
        return "40%+"

    
# Apply the function to the Discount column.

df["Discount Band"] = df["Discount"].apply(classify_discount)


# Check how many records fall into each discount band.

df["Discount Band"].value_counts()

Discount Band
0%        4798
1-20%     3803
40%+       933
21-40%     460
Name: count, dtype: int64

In [29]:
# Display all column names in the dataset.
# This allows us to confirm that our newly created
# analytical columns have been added successfully.

df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Delivery Days',
 'Year',
 'Month',
 'Month-Year',
 'Profit Margin %',
 'Profit/Loss Status',
 'Discount Band']

In [30]:
# Save the cleaned and enriched dataset as a new CSV file.
# We keep the original Sample - Superstore.csv unchanged.
#
# index=False prevents pandas from creating an extra index column
# in the exported CSV file.

df.to_csv(
    "Superstore_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [31]:
# Read the newly created CSV file back into pandas.
# This verifies that the exported file can be opened successfully.

df_check = pd.read_csv(
    "Superstore_Cleaned.csv",
    encoding="latin1"
)

# Display the number of rows and columns.

print("Rows:", df_check.shape[0])
print("Columns:", df_check.shape[1])

Rows: 9994
Columns: 28